require("vincent.plugins-setup")
require("vincent.core.options")
require("vincent.core.keymaps")
require("vincent.core.colorscheme")
require("vincent.plugins.nvim-tree")
require("vincent.plugins.lualine")
require("vincent.plugins.telescope")
require("vincent.plugins.treesitter")
